import type { INodeProperties } from 'n8n-workflow';

export const clientsDescription: INodeProperties[] = [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					]
				}
			},
			"options": [
				{
					"name": "Client Options",
					"value": "Client Options",
					"action": "Gets languages supported by the client generator",
					"description": "Gets languages supported by the client generator",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/gen/clients"
						}
					}
				},
				{
					"name": "Get Client Options",
					"value": "Get Client Options",
					"action": "Returns options for a client library",
					"description": "Returns options for a client library",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/gen/clients/{{$parameter[\"language\"]}}"
						}
					}
				},
				{
					"name": "Generate Client",
					"value": "Generate Client",
					"action": "Generates a client library",
					"description": "Accepts a `GeneratorInput` options map for spec location and generation options",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/api/gen/clients/{{$parameter[\"language\"]}}"
						}
					}
				},
				{
					"name": "Download File",
					"value": "Download File",
					"action": "Downloads a pre-generated file",
					"description": "A valid `fileId` is generated by the `/clients/{language}` or `/servers/{language}` POST operations.  The fileId code can be used just once, after which a new `fileId` will need to be requested.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/gen/download/{{$parameter[\"fileId\"]}}"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "GET /api/gen/clients",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Client Options"
					]
				}
			}
		},
		{
			"displayName": "GET /api/gen/clients/{language}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Get Client Options"
					]
				}
			}
		},
		{
			"displayName": "Language",
			"name": "language",
			"required": true,
			"description": "The target language for the client library",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Get Client Options"
					]
				}
			}
		},
		{
			"displayName": "POST /api/gen/clients/{language}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Generate Client"
					]
				}
			}
		},
		{
			"displayName": "Language",
			"name": "language",
			"required": true,
			"description": "The target language for the client library",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Generate Client"
					]
				}
			}
		},
		{
			"displayName": "Authorization Value",
			"name": "authorizationValue",
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"property": "authorizationValue",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Generate Client"
					]
				}
			}
		},
		{
			"displayName": "Open API URL",
			"name": "openAPIUrl",
			"type": "string",
			"default": "https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml",
			"routing": {
				"send": {
					"property": "openAPIUrl",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Generate Client"
					]
				}
			}
		},
		{
			"displayName": "Options",
			"name": "options",
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"property": "options",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Generate Client"
					]
				}
			}
		},
		{
			"displayName": "Spec",
			"name": "spec",
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"property": "spec",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Generate Client"
					]
				}
			}
		},
		{
			"displayName": "GET /api/gen/download/{fileId}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Download File"
					]
				}
			}
		},
		{
			"displayName": "File ID",
			"name": "fileId",
			"required": true,
			"description": "fileId",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Clients"
					],
					"operation": [
						"Download File"
					]
				}
			}
		},
];
