import type { INodeProperties } from 'n8n-workflow';

export const serversDescription: INodeProperties[] = [
		{
			"displayName": "Operation",
			"name": "operation",
			"type": "options",
			"noDataExpression": true,
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					]
				}
			},
			"options": [
				{
					"name": "Download File",
					"value": "Download File",
					"action": "Downloads a pre-generated file",
					"description": "A valid `fileId` is generated by the `/clients/{language}` or `/servers/{language}` POST operations.  The fileId code can be used just once, after which a new `fileId` will need to be requested.",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/gen/download/{{$parameter[\"fileId\"]}}"
						}
					}
				},
				{
					"name": "Server Options",
					"value": "Server Options",
					"action": "Gets languages supported by the server generator",
					"description": "Gets languages supported by the server generator",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/gen/servers"
						}
					}
				},
				{
					"name": "Get Server Options",
					"value": "Get Server Options",
					"action": "Returns options for a server framework",
					"description": "Returns options for a server framework",
					"routing": {
						"request": {
							"method": "GET",
							"url": "=/api/gen/servers/{{$parameter[\"framework\"]}}"
						}
					}
				},
				{
					"name": "Generate Server For Language",
					"value": "Generate Server For Language",
					"action": "Generates a server library",
					"description": "Accepts a `GeneratorInput` options map for spec location and generation options.",
					"routing": {
						"request": {
							"method": "POST",
							"url": "=/api/gen/servers/{{$parameter[\"framework\"]}}"
						}
					}
				}
			],
			"default": ""
		},
		{
			"displayName": "GET /api/gen/download/{fileId}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Download File"
					]
				}
			}
		},
		{
			"displayName": "File ID",
			"name": "fileId",
			"required": true,
			"description": "fileId",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Download File"
					]
				}
			}
		},
		{
			"displayName": "GET /api/gen/servers",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Server Options"
					]
				}
			}
		},
		{
			"displayName": "GET /api/gen/servers/{framework}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Get Server Options"
					]
				}
			}
		},
		{
			"displayName": "Framework",
			"name": "framework",
			"required": true,
			"description": "The target language for the server framework",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Get Server Options"
					]
				}
			}
		},
		{
			"displayName": "POST /api/gen/servers/{framework}",
			"name": "operation",
			"type": "notice",
			"typeOptions": {
				"theme": "info"
			},
			"default": "",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Generate Server For Language"
					]
				}
			}
		},
		{
			"displayName": "Framework",
			"name": "framework",
			"required": true,
			"description": "framework",
			"default": "",
			"type": "string",
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Generate Server For Language"
					]
				}
			}
		},
		{
			"displayName": "Authorization Value",
			"name": "authorizationValue",
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"property": "authorizationValue",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Generate Server For Language"
					]
				}
			}
		},
		{
			"displayName": "Open API URL",
			"name": "openAPIUrl",
			"type": "string",
			"default": "https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml",
			"routing": {
				"send": {
					"property": "openAPIUrl",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ $value }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Generate Server For Language"
					]
				}
			}
		},
		{
			"displayName": "Options",
			"name": "options",
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"property": "options",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Generate Server For Language"
					]
				}
			}
		},
		{
			"displayName": "Spec",
			"name": "spec",
			"type": "json",
			"default": "{}",
			"routing": {
				"send": {
					"property": "spec",
					"propertyInDotNotation": false,
					"type": "body",
					"value": "={{ JSON.parse($value) }}"
				}
			},
			"displayOptions": {
				"show": {
					"resource": [
						"Servers"
					],
					"operation": [
						"Generate Server For Language"
					]
				}
			}
		},
];
